/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import Business.*;
import java.util.regex.*;
import javax.swing.JOptionPane;


/**
 *
 * @author jauzh
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form creatPersonJPanel
     * 
     */
    private Patient patient;
    public CreatePatientJPanel(Patient p) {
        initComponents();
        patient=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPatientjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doctorNamejLabel = new javax.swing.JLabel();
        pharmacyjLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        idjTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        doctorNamejTextField = new javax.swing.JTextField();
        pharmacyjTextField = new javax.swing.JTextField();
        createPatientjButton = new javax.swing.JButton();

        createPatientjLabel.setText("Create Patient");

        namejLabel.setText("Name");

        idjLabel.setText("ID");

        jLabel3.setText("Age");

        doctorNamejLabel.setText("Doctor Name");

        pharmacyjLabel.setText("Pharmacy");

        createPatientjButton.setText("Creat Patient");
        createPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(createPatientjLabel)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pharmacyjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createPatientjButton)
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(idjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doctorNamejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pharmacyjTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(createPatientjLabel)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorNamejLabel)
                    .addComponent(doctorNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pharmacyjLabel)
                    .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(createPatientjButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientjButtonActionPerformed
        // TODO add your handling code here:
        
        // check the input values
        boolean isInputValid = true;
        if(this.namejTextField.getText().trim().compareTo("") == 0) isInputValid = false;
        if(this.idjTextField.getText().trim().compareTo("") == 0) isInputValid = false;
        if(this.doctorNamejTextField.getText().trim().compareTo("")==0) isInputValid = false;
        if(this.pharmacyjTextField.getText().trim().compareTo("")==0)isInputValid = false;
        if(this.agejTextField.getText().trim().compareTo("") == 0 &&
                !isInteger(this.agejTextField.getText().trim())) 
            isInputValid = false;
               
       if(!isInputValid){
             JOptionPane.showMessageDialog(null, "Please enter valid value!");
             return; 
        }

        
        patient.setName(namejTextField.getText());
        patient.setId(idjTextField.getText());
        patient.setAge(Integer.parseInt(agejTextField.getText()));
        patient.setDoctorName(doctorNamejTextField.getText());
        patient.setPharmacy(pharmacyjTextField.getText());
        patient.setVitalSignHistory(new VitalSignHistory());
        
    }//GEN-LAST:event_createPatientjButtonActionPerformed

    private boolean isInteger(String s){
        Pattern p = Pattern.compile("/d*");
        Matcher m = p.matcher(s);
        return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton createPatientjButton;
    private javax.swing.JLabel createPatientjLabel;
    private javax.swing.JLabel doctorNamejLabel;
    private javax.swing.JTextField doctorNamejTextField;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel pharmacyjLabel;
    private javax.swing.JTextField pharmacyjTextField;
    // End of variables declaration//GEN-END:variables
}
