/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import Business.Patient;
import Business.VitalSign;
import Business.VitalSignHistory;
import java.util.regex.*;
import javax.swing.JOptionPane;


/**
 *
 * @author jauzh
 */
public class CreateVitalSignJPanel extends javax.swing.JPanel {
    private Patient patient;
    

    /**
     * Creates new form createVitalSignJPanel
     */
    public CreateVitalSignJPanel(Patient patient) {
        initComponents();
        this.patient=patient;
        
        this.namejTextField.setText(patient.getName());
        this.idjTextField.setText(patient.getId());
        this.agejTextField.setText(String.valueOf(patient.getAge()));
        this.doctorNamejTextField.setText(patient.getDoctorName());
        this.pharmacyjTextField.setText(patient.getPharmacy());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respiratoryjLabel = new javax.swing.JLabel();
        heartRatejLabel = new javax.swing.JLabel();
        systolicBloodPressurejLabel = new javax.swing.JLabel();
        weightjLabel = new javax.swing.JLabel();
        timejLabel = new javax.swing.JLabel();
        respiratoryRatejTextField = new javax.swing.JTextField();
        heartRatejTextField = new javax.swing.JTextField();
        systolicBloodPressurejTextField = new javax.swing.JTextField();
        weightjTextField = new javax.swing.JTextField();
        timejTextField = new javax.swing.JTextField();
        createVitalSignjLabel = new javax.swing.JLabel();
        createVitalSignjButton = new javax.swing.JButton();
        namejLabel = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        agejLabel = new javax.swing.JLabel();
        doctorNamejLabel = new javax.swing.JLabel();
        pharmacyjLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        idjTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        doctorNamejTextField = new javax.swing.JTextField();
        pharmacyjTextField = new javax.swing.JTextField();

        respiratoryjLabel.setText("Respiratory Rate");

        heartRatejLabel.setText("Heart Rate");

        systolicBloodPressurejLabel.setText("Systolic Pressure");

        weightjLabel.setText("Weight");

        timejLabel.setText("Time");

        createVitalSignjLabel.setText("Create Vital Sign");

        createVitalSignjButton.setText("Create Vital Sign");
        createVitalSignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVitalSignjButtonActionPerformed(evt);
            }
        });

        namejLabel.setText("Name");

        idjLabel.setText("ID");

        agejLabel.setText("Age");

        doctorNamejLabel.setText("Doctor Name");

        pharmacyjLabel.setText("Pharmacy");

        namejTextField.setEditable(false);

        idjTextField.setEditable(false);

        agejTextField.setEditable(false);

        doctorNamejTextField.setEditable(false);

        pharmacyjTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respiratoryjLabel)
                    .addComponent(systolicBloodPressurejLabel)
                    .addComponent(heartRatejLabel)
                    .addComponent(weightjLabel)
                    .addComponent(timejLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pharmacyjLabel)
                        .addComponent(doctorNamejLabel)
                        .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addComponent(idjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightjTextField)
                    .addComponent(timejTextField)
                    .addComponent(respiratoryRatejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(heartRatejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(systolicBloodPressurejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namejTextField)
                    .addComponent(idjTextField)
                    .addComponent(agejTextField)
                    .addComponent(doctorNamejTextField)
                    .addComponent(pharmacyjTextField))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(createVitalSignjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(createVitalSignjButton)))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(createVitalSignjLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agejLabel)
                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorNamejLabel)
                    .addComponent(doctorNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pharmacyjLabel)
                    .addComponent(pharmacyjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respiratoryjLabel)
                    .addComponent(respiratoryRatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heartRatejLabel)
                    .addComponent(heartRatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systolicBloodPressurejLabel)
                    .addComponent(systolicBloodPressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timejLabel))
                .addGap(18, 18, 18)
                .addComponent(createVitalSignjButton)
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createVitalSignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVitalSignjButtonActionPerformed
        // TODO add your handling code here:
        boolean isInputValid = true;
        if(this.respiratoryRatejTextField.getText().trim().compareTo("") == 0 &&
                !isInteger(this.respiratoryRatejTextField.getText().trim())) 
            isInputValid = false;
        if(this.heartRatejTextField.getText().trim().compareTo("") == 0 &&
                !isInteger(this.heartRatejTextField.getText().trim())) 
            isInputValid = false;
        if(this.systolicBloodPressurejTextField.getText().trim().compareTo("") == 0 &&
                !isInteger(this.systolicBloodPressurejTextField.getText().trim())) 
            isInputValid = false;
        if(this.weightjTextField.getText().trim().compareTo("") == 0 &&
                !isInteger(this.weightjTextField.getText().trim())) 
            isInputValid = false;
        
         if(!isInputValid){
             JOptionPane.showMessageDialog(null, "Please enter valid value!");
             return; 
        }
                
        int respiratoryRate=Integer.parseInt(respiratoryRatejTextField.getText());
        int heartRate=Integer.parseInt(heartRatejTextField.getText());
        int systolicBloodPressure=Integer.parseInt(systolicBloodPressurejTextField.getText());
        int weight=Integer.parseInt(weightjTextField.getText());
        String time=timejTextField.getText();
        VitalSign vs = new VitalSign(respiratoryRate,heartRate,systolicBloodPressure,weight,time);
        vs.diagnose(patient.getAge());
        patient.getVitalSignHistory().addVitalSign(vs);
        
    }//GEN-LAST:event_createVitalSignjButtonActionPerformed
       //create a method to chech whether integer input is valid
       private boolean isInteger(String s){
            Pattern p = Pattern.compile("/d*");
            Matcher m = p.matcher(s);
            return m.matches();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agejLabel;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton createVitalSignjButton;
    private javax.swing.JLabel createVitalSignjLabel;
    private javax.swing.JLabel doctorNamejLabel;
    private javax.swing.JTextField doctorNamejTextField;
    private javax.swing.JLabel heartRatejLabel;
    private javax.swing.JTextField heartRatejTextField;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel pharmacyjLabel;
    private javax.swing.JTextField pharmacyjTextField;
    private javax.swing.JTextField respiratoryRatejTextField;
    private javax.swing.JLabel respiratoryjLabel;
    private javax.swing.JLabel systolicBloodPressurejLabel;
    private javax.swing.JTextField systolicBloodPressurejTextField;
    private javax.swing.JLabel timejLabel;
    private javax.swing.JTextField timejTextField;
    private javax.swing.JLabel weightjLabel;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
