/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;
import Business.Patient;
import Business.VitalSignHistory;

/**
 *
 * @author jauzh
 */
public class MainJFrame extends javax.swing.JFrame {
    private Patient patient;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.patient=new Patient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftjPanel = new javax.swing.JPanel();
        createVitalSignjButton = new javax.swing.JButton();
        viewVitalSignjButton = new javax.swing.JButton();
        createPatientjButton = new javax.swing.JButton();
        rightjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        createVitalSignjButton.setText("Creat Vital Sgn");
        createVitalSignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVitalSignjButtonActionPerformed(evt);
            }
        });

        viewVitalSignjButton.setText("View Vital Sign");
        viewVitalSignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignjButtonActionPerformed(evt);
            }
        });

        createPatientjButton.setText("Create Patient");
        createPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftjPanelLayout = new javax.swing.GroupLayout(leftjPanel);
        leftjPanel.setLayout(leftjPanelLayout);
        leftjPanelLayout.setHorizontalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createVitalSignjButton)
                    .addComponent(viewVitalSignjButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftjPanelLayout.createSequentialGroup()
                .addComponent(createPatientjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftjPanelLayout.setVerticalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(createPatientjButton)
                .addGap(47, 47, 47)
                .addComponent(createVitalSignjButton)
                .addGap(95, 95, 95)
                .addComponent(viewVitalSignjButton)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftjPanel);

        rightjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setRightComponent(rightjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createVitalSignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVitalSignjButtonActionPerformed
        // TODO add your handling code here:
        CreateVitalSignJPanel cvjp=new CreateVitalSignJPanel(patient);
        jSplitPane1.setRightComponent(cvjp);
    }//GEN-LAST:event_createVitalSignjButtonActionPerformed

    private void viewVitalSignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignjButtonActionPerformed
        // TODO add your handling code here:
        ViewVitalSignJPanel vpjp=new ViewVitalSignJPanel(patient);
        jSplitPane1.setRightComponent(vpjp);
    }//GEN-LAST:event_viewVitalSignjButtonActionPerformed

    private void createPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientjButtonActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel cpjp=new CreatePatientJPanel(patient);
        jSplitPane1.setRightComponent(cpjp);
    }//GEN-LAST:event_createPatientjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPatientjButton;
    private javax.swing.JButton createVitalSignjButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftjPanel;
    private javax.swing.JPanel rightjPanel;
    private javax.swing.JButton viewVitalSignjButton;
    // End of variables declaration//GEN-END:variables
}
